#!/usr/bin/env python3
"""The AmiBSDNet release version.

  python -I tools/version.py            writes build/gen/amibsdnet_version.h
  python -I tools/version.py --print    prints the version

The header defines AMIBSDNET_VERSION, AMIBSDNET_DATE and
AMIBSDNET_VERSTAG(name), the "$VER:" string of a program called name.
"""
import os
import sys

VERSION = "0.8.4"
DATE = "10.10.2026"        # AmigaOS version string date: day.month.year

TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(TOP, "build", "gen", "amibsdnet_version.h")


def header_text():
    return (
        "/* generated by tools/version.py: do not edit */\n"
        "#ifndef AMIBSDNET_VERSION_H\n"
        "#define AMIBSDNET_VERSION_H\n"
        f"#define\tAMIBSDNET_VERSION\t\"{VERSION}\"\n"
        f"#define\tAMIBSDNET_DATE\t\"{DATE}\"\n"
        "/* \"$VER: <name> <version> (<date>)\" for a program called name */\n"
        "#define\tAMIBSDNET_VERSTAG(name)\t\\\n"
        "\t\"\\0$VER: \" name \" \" AMIBSDNET_VERSION \" (\" AMIBSDNET_DATE \")\"\n"
        "#endif\n")


def write_header():
    text = header_text()
    os.makedirs(os.path.dirname(HEADER), exist_ok=True)
    if os.path.exists(HEADER):
        with open(HEADER, newline="") as f:
            if f.read() == text:
                return HEADER
    with open(HEADER, "w", newline="\n") as f:
        f.write(text)
    return HEADER


if __name__ == "__main__":
    if "--print" in sys.argv[1:]:
        print(VERSION)
    else:
        write_header()
